// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatAnimationController from "./chat_animation_controller"
application.register("chat-animation", ChatAnimationController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InvitationController from "./invitation_controller"
application.register("invitation", InvitationController)

import MobileMenuController from "./mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import PushNotificationController from "./push_notification_controller"
application.register("push-notification", PushNotificationController)

import RewardConditionFormController from "./reward_condition_form_controller"
application.register("reward-condition-form", RewardConditionFormController)

import TurboNativeController from "./turbo_native_controller"
application.register("turbo-native", TurboNativeController)

import UrlCopyController from "./url_copy_controller"
application.register("url-copy", UrlCopyController)
