:concurrency: 5
:queues:
  - default
:scheduler:
  :schedule:
    get_notification_targets:
      cron: '*/30 * * * *'
      class: GetNotificationTargetsJob
      queue: default
      description: '30分毎に通知対象を取得'